language: go

go:
 - "1.11.x"

before_install:
  - go get -u github.com/alecthomas/gometalinter
  - go get github.com/mattn/goveralls

install:
  - gometalinter --install

script:
 - gometalinter --fast --vendor ./...
 - go test ./... -coverprofile cover.out -covermode count -coverpkg ./...
  
after_script:
  - goveralls -v -coverprofile cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
